model_id: "Qwen/Qwen2.5-7B-Instruct"
data_path: "pablomiralles22/anli-bootstrap-qwen-7b-difficult"
data_split: "train"
run_name: ???
use_checkpoint: false
micro_batch_size: 1
prompt_config: "configs/prompts/deepseek.yaml"
output_dir: "out/rl_train/v2"

lora_config:
  r: 64
  lora_alpha: 64
  lora_dropout: 0.0
  target_modules: "all-linear"

trainer_config:
  logging_steps: 1
  save_steps: 250
  save_only_model: false
  overwrite_output_dir: true
  report_to: "none"
  log_completions: false
  save_total_limit: 1

  num_train_epochs: 1

  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_generations: 4
  gradient_accumulation_steps: 1
  # use_vllm: true

  optim: "paged_adamw_8bit"
  learning_rate: 5.e-6
  max_grad_norm: 1.0
  max_completion_length: 512
  warmup_steps: 50
  max_steps: 1000
  beta: 0.01
  num_iterations: 4
  epsilon: 0.2
  scale_rewards: false

  model_init_kwargs:
    device_map: auto
    torch_dtype: float16
    attn_implementation: flash_attention_2

  fp16: false
  bf16: true
  torch_empty_cache_steps: 1

hydra:
  run:
    dir: ./out/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}