model:
  num_frozen_layers: 14

optimizer:
  lr: 3.e-5
  weight_decay: 1.e-4

  scheduler:
    name: constant_with_warmup
    num_warmup_steps: 500

trainer:
  max_epochs: 3
  accelerator: gpu
  devices: [0]
  precision: 16-mixed
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  val_check_interval: 0.25

data_module:
  data_path: pablomiralles22/anli-bootstrap-qwen-14b
  batch_size: 8
  max_length: 512
  mlm_probability: 0.5

output_dir: out/multitask_encoder